// <auto-generated />
namespace ATS.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _64654 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_64654));
        
        string IMigrationMetadata.Id
        {
            get { return "201710120655500_64654"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
